### PR TITLE
Archlinux build

### PR DESCRIPTION
**Pull request by rodneyp290**
All seems to run well on my Arch Linux system, except 66% tests passed.
See attached text file for summary extract ctest output.
[ctest-summary.txt](https://github.com/Microsoft/malmo/files/406654/ctest-summary.txt)

### CODE REVIEW

**Comment by DaveyBiggers** [comment]
Thank you so much for doing this! I'll take a look at the failing tests.

**Comment by rodneyp290** [comment]
Should I rebase my branch so this pull request is up to date?

**Comment by DaveyBiggers** [comment]
Sorry Rodney, I meant to check out those failing tests but haven't quite got around to getting myself a working Arch VM yet.
The PR only touches the documentation, which hasn't changed significantly if I recall correctly, so I wouldn't worry too much about rebasing for now.

**Comment by DaveyBiggers** [comment]
Thanks Rodney! Sorry we left this languishing for so long... have been meaning to test this with an Arch VM but it never happened. Am now briefly revisiting the build process, and it makes sense to take your changes before anything happens that will cause merge conflicts with them.

**Pull request merged**
