### PR TITLE
Added life to observations of living entities.

### PR DESCRIPTION
**Pull request by StStevens**
I added a simple check to add life to the observations from living entities similar to the check for item stack specific values.

I'm working on a project with player/entity interaction and couldn't find any other way to get the life of an entity.

### CODE REVIEW

**Comment by Lesita** [comment]
OK. But seems like that a mew 'LICENSE AGREEMENT' established?

来自Cyanogenmod Mail

Microsoft Contribution License Agreements <notifications@github.com>编写：

**Comment by DaveyBiggers** [comment]
@StStevens great, thanks for this!
Could you also check/update the python samples? There are a few which use `namedtuple` for parsing the entities, which I think will break unless the new field is added to them.
Cheers!

**Comment by StStevens** [comment]
@DaveyBiggers  You were correct about that breaking examples. I took a look and updated all the 4 python examples that used namedtuple for parsing and added another field to the EntityInfo namedtuple. I also updated the reward_from_items example to be the same as the other 3 files even though the fields are unused.

**Comment by DaveyBiggers** [comment]
Brilliant, thanks so much for this, and for cleaning up reward_from_items.

**Pull request merged**
