### PR TITLE
Go (golang) wrapper

### PR DESCRIPTION
**Pull request by cpmech**
Hello everyone,

I've created this wrapper to the Go language and thought you'd be interested.

I'm planning to write all the examples from the Python directory as well.

Kind regards,
Dorival

### CODE REVIEW

**Comment by cpmech** [comment]
Hello,

I just would like to let you know that the file structure now is consistent across the project; i.e. GoWrapper, Go_examples, and GoTests have been created in src, samples, and test, respectively.

Also, I create a CMakeLists.txt to build and install the GoWrapper in the same way as the other wrappers. The root CMakeLists.txt has been modified with the GO option accordingly. (CMake should work fine)

Cheers.
Dorival

**Comment by DaveyBiggers** [comment]
Hi Dorival, this is fantastic! Thanks for all this hard work.
Rather than wrapping the Malmo code manually, could we use Swig instead? (http://www.swig.org/Doc2.0/Go.html)
This is how we create the bindings for Java and C# - for example, look at https://github.com/Microsoft/malmo/blob/master/Malmo/src/JavaWrapper/MalmoJava.i - and it should be possible to do the same for Go.
Aside from saving a lot of typing (which you've already done, sorry!), it's far more maintainable, since everything is driven off the C++ code and we don't have to maintain parallel sets of methods/classes etc.

The Go ports of the python samples will be incredibly useful, thank you - we always planned to port the samples to the other languages but somehow we never got very far...

**Comment by cpmech** [comment]
Hi David,

Thanks!

Sure! I agree that the "manual Go wrapper" is harder to maintain. I've tried Swig before and am looking at it again (version 3.0.8), but got stuck with boost_shared_ptr.i that doesn't exist for Go (I'm reading the csharp version of boost_shared_ptr.i right now, and it looks very scary to me). Well, I'm not too familiar with Swig either...

I'm thinking about creating a script to automatise the Go wrapper for the time being in order to synchronise with the C++ files. I also want to write all samples in Go (to learn and to see where my Goga code could be used).

And, please, it's OK to wait for an alternative/future pull request using swig! No worries!

Cheers.
Dorival

**Comment by cpmech** [comment]
I'll try developing a Go Wrapper again using Swig. Thus, this code+request can be deleted. Cheers.

**Pull request closed without merging**
